### ISSUE TITLE
does not work on windows with xampp

### ISSUE THREAD

**Issue by jerson** [scaliaes/Vevui#11]
I downloaded the framework, but does not work, mine is a mistake talves but entered the following path:

http://localhost/Vevui/pub/index.php/main/index/
or
http://localhost/Vevui/pub/index.php/sample/

but nothing is displayed

**Comment by jerson** [comment]
Sorry I forget to download Haanga, now works fine

**Comment by dvigueras** [comment]
I didn't see this issue until now. 
Haanga is included as a git submodule, so you have to initialize and update it :)

There is no documentation yet about developing with Vevui, if you need any help just ask.
